
CFLAGS=-g -Wall -Wextra -O2 `pkg-config --cflags /home/a/W/W.priv/Shared/openmpi-4.0.0/lib/pkgconfig/ompi.pc`
LDFLAGS=`pkg-config --libs /home/a/W/W.priv/Shared/openmpi-4.0.0/lib/pkgconfig/ompi.pc`
CC=gcc
CXX=g++

all:
	$(CXX) $(CFLAGS) main.cpp $(LDFLAGS) 
